export enum RouteEnum {
  HOME = '/',
  LOGIN = '/login',
  REGISTER = '/register',
  FORGOT_PASSWORD = '/forgot-password',
  DASHBOARD = '/dashboard',
  VOCABULARY = '/dashboard/vocabulary',
  DECKS = '/dashboard/decks',
  STUDY = '/dashboard/study',
  QUIZ = '/dashboard/quiz',
  TOEIC = '/dashboard/toeic',
  READING = '/dashboard/reading',
  DICTATION = '/dashboard/dictation',
  PROFILE = '/dashboard/profile',
  SETTINGS = '/dashboard/settings',
}
