export enum RouteEnum {
  HOME = '/',
  LOGIN = '/login',
  REGISTER = '/register',
  FORGOT_PASSWORD = '/forgot-password',
  RESET_PASSWORD = '/reset-password',
  DASHBOARD = '/overview',
  VOCABULARY = '/vocabulary',
  DECKS = '/decks',
  DECK_DETAIL = '/vocabulary/decks/:id',
  STUDY = '/study',
  QUIZ = '/quiz',
  QUIZ_SESSION = '/quiz/:id',
  TOEIC = '/toeic',
  TOEIC_TEST = '/toeic/:id',
  EXAM_RESULT = '/toeic/:id/result',
  READING = '/reading',
  ARTICLE_READER = '/reading/:id',
  DICTATION = '/dictation',
  DICTATION_EXERCISE = '/dictation/:id',
  FLASHCARD_REVIEW = '/vocabulary/review',
  PROFILE = '/profile',
  SETTINGS = '/settings',
  GRAMMAR = '/grammar',
  GRAMMAR_TOPIC = '/grammar/:id',
  SPEAKING = '/speaking',
  SPEAKING_TASK = '/speaking/:id',
}
